language: generic

os: osx

# rvm:
# - 2.1.2

branches:
  only:
  - gh-pages
  - /.*/

before_install:
- chmod a+x ./install.sh
- chmod a+x "./Serious Nutrition Game/build.sh"

install: travis_wait 30 ./install.sh

script:
  - ./Serious\ Nutrition\ Game/build.sh

# deploy:
#   provider: s3
#   access_key_id: AKIAITEPAI7MBUKSYRMQ
#   secret_access_key:
#     secure: ki6uIaFaL6dwExiC0HpTa5K2+YP8WNeWbjFSZBTZQub4esPYlmkw8JGsqLGOv+1ics2SaL+ZUxyP0ivRfUO3hzvFPuVb/iLU3tvmBJuGmSz411suvCOkK7OOA5gxrUr9oM0Y3Z/827OVHZmUIB2Plun/KU1PZ94KNPFDQce9yQA=
#   bucket: dev.jonathan.porta.codes
#   local-dir: Build
#   upload-dir: ci-build
#   skip_cleanup: true
#   acl: public_read
#   on:
#     repo: JonathanPorta/ci-build
